"""Pure, MCP-framework-free implementations of the tools exposed over MCP.

Kept separate from :mod:`scope_profiler.mcp_server.server` so these functions
can be unit-tested (and reused) without importing the ``mcp`` package at all,
and so the MCP layer stays a thin adapter over the existing
``scope_profiler`` Python API rather than a place where new profiling,
HDF5-parsing, summary or comparison logic gets written. Every function here
delegates the actual computation to :mod:`scope_profiler.summary`,
:mod:`scope_profiler.diff`, :mod:`scope_profiler.inspection`,
:mod:`scope_profiler.results` or :mod:`scope_profiler.plotting_scripts`.

Every public function returns plain, JSON-serializable ``dict``/``list``
data (or raises :class:`ToolError`) -- never terminal-formatted text -- so an
agent gets structured values it can act on directly instead of having to
parse a table.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

from scope_profiler.benchmark import (
    BenchmarkError,
)
from scope_profiler.benchmark import compare_benchmarks as _compare_benchmarks
from scope_profiler.benchmark import (
    load_config,
)
from scope_profiler.benchmark import run_benchmark as _run_benchmark
from scope_profiler.diff import METRICS as DIFF_METRICS
from scope_profiler.diff import diff_rows
from scope_profiler.h5reader import read_h5
from scope_profiler.inspection import (
    _metadata_sections,
    _time_span,
    collect_file_metadata,
)
from scope_profiler.results import ProfilingResults
from scope_profiler.summary import SORT_KEYS, region_rows

#: Default cap on how many region rows a tool returns, to keep responses
#: small enough for an LLM context window; callers can raise ``top_n`` to see
#: more.
_DEFAULT_TOP_N = 20

#: The five plot types generated by default by ``scope-profiler plot`` (see
#: ``post_processing._PLOT_CATALOG``); the opt-in ones (histogram, imbalance,
#: likwid) are left out of the MCP surface to keep it small -- an agent that
#: needs those can still be pointed at the CLI.
_PLOT_FUNCS = {
    "gantt": "plot_gantt",
    "flame": "plot_flame",
    "durations": "plot_durations",
    "timeseries": "plot_duration_timeseries",
    "speedup": "plot_speedup",
}


class ToolError(Exception):
    """A user-facing error from an MCP tool (bad input, missing file, ...)."""


def run_benchmark(config_path: str, label: str = "candidate") -> dict:
    """Run a declarative repeated benchmark and correctness gate."""
    try:
        return _run_benchmark(load_config(config_path), label=label)
    except BenchmarkError as exc:
        raise ToolError(str(exc)) from exc


def compare_benchmarks(baseline_path: str, candidate_path: str) -> dict:
    """Compare benchmark manifests and return a keep/reject decision."""
    try:
        return _compare_benchmarks(baseline_path, candidate_path)
    except (BenchmarkError, OSError, ValueError, KeyError, json.JSONDecodeError) as exc:
        raise ToolError(f"Could not compare benchmark manifests: {exc}") from exc


def _read_profile(file_path: str) -> ProfilingResults:
    """Load a profiling file, translating failures into a :class:`ToolError`."""
    try:
        return read_h5(file_path)
    except FileNotFoundError as exc:
        raise ToolError(str(exc)) from exc
    except (
        Exception
    ) as exc:  # noqa: BLE001 - h5py/attribute errors vary by failure mode
        raise ToolError(
            f"Could not read {file_path!r} as a profiling file: {exc}"
        ) from exc


def _profile_headline(results: ProfilingResults) -> dict:
    """The handful of top-level numbers every tool that touches a file returns."""
    return {
        "file_path": str(results.file_path),
        "label": results.display_label,
        "num_ranks": results.num_ranks,
        "num_regions": len(results.get_regions()),
        "total_time_seconds": results.total_time,
        "wall_clock_seconds": _time_span(results),
    }


def _metadata_payload(results: ProfilingResults, full: bool) -> dict:
    """Group a run's metadata the way ``scope-profiler inspect`` does.

    ``full=False`` (the default) drops the "Environment"/"Other" sections --
    raw environment variables and unrecognized fields, which are rarely
    useful to an agent and can be large (``PATH``, ``LD_LIBRARY_PATH``, ...)
    -- keeping just their counts, plus the run/system/parallelism/Slurm
    fields and the loaded module list.
    """
    metadata = collect_file_metadata(results)["files"][0]["metadata"]
    sections, modules = _metadata_sections(metadata)

    payload = {}
    for title, entries in sections:
        key = title.lower()
        if not full and key in ("environment", "other"):
            if entries:
                payload[f"{key}_field_count"] = len(entries)
            continue
        if entries:
            payload[key] = dict(entries)
    if modules is not None:
        payload["modules"] = list(modules)
    return payload


def _likwid_payload(
    results: ProfilingResults, ranks=None, top_n: int | None = None
) -> dict | None:
    """Structured LIKWID summary, or ``None`` when the run recorded none.

    Per-thread metric/event values are averaged across threads (a region
    with several OpenMP threads has one column per thread in the file) to
    keep the payload small and easy for an agent to reason about; the raw
    per-thread arrays remain available from Python via
    :meth:`ProfilingResults.get_likwid_region`.
    """
    if not results.has_likwid:
        return None

    likwid_ranks = results.likwid_ranks
    if ranks is not None:
        likwid_ranks = [rank for rank in likwid_ranks if rank in ranks]

    entries = []
    for rank in likwid_ranks:
        for tag, region in results.get_likwid_regions(rank=rank).items():
            entries.append(
                {
                    "rank": rank,
                    "region": tag,
                    "group": region.group_name,
                    "call_count": int(np.sum(region.call_counts)),
                    "metrics": {
                        name: float(np.mean(values))
                        for name, values in zip(region.metric_names, region.metrics)
                    },
                }
            )
    entries.sort(key=lambda entry: (entry["rank"], entry["region"]))

    total = len(entries)
    if top_n is not None:
        entries = entries[:top_n]

    return {
        "ranks": likwid_ranks,
        "region_count_total": total,
        "region_count_returned": len(entries),
        "regions": entries,
    }


def inspect_profile(
    file_path: str,
    include: list[str] | None = None,
    exclude: list[str] | None = None,
    ranks: list[int] | None = None,
    sort: str = "total",
    top_n: int | None = _DEFAULT_TOP_N,
    full_metadata: bool = False,
) -> dict:
    """Structured summary of one profiling file: metadata + region statistics.

    Reuses :func:`scope_profiler.summary.region_rows` and
    :func:`scope_profiler.inspection.collect_file_metadata` -- the same data
    ``scope-profiler inspect`` prints -- without any text formatting.
    """
    if sort not in SORT_KEYS:
        raise ToolError(f"sort must be one of {SORT_KEYS}, got {sort!r}")
    if top_n is not None and top_n < 1:
        raise ToolError("top_n must be a positive integer, or None/0 for no limit")

    results = _read_profile(file_path)

    rows = region_rows(
        results, include=include, exclude=exclude, ranks=ranks, sort=sort
    )
    total_matching = len(rows)
    limited = rows[:top_n] if top_n else rows

    payload = _profile_headline(results)
    payload["metadata"] = _metadata_payload(results, full=full_metadata)
    payload["regions"] = {
        "sort": sort,
        "returned": len(limited),
        "total_matching_filter": total_matching,
        "items": limited,
    }
    payload["likwid"] = _likwid_payload(results, ranks=ranks, top_n=top_n)
    return payload


def compare_profiles(
    baseline_path: str,
    candidate_path: str,
    include: list[str] | None = None,
    exclude: list[str] | None = None,
    ranks: list[int] | None = None,
    metric: str = "total",
    threshold_pct: float = 5.0,
    top_n: int | None = _DEFAULT_TOP_N,
) -> dict:
    """Machine-readable performance diff between two profiling files.

    Reuses :func:`scope_profiler.diff.diff_rows` for the per-region deltas,
    then computes the overall (whole-run) comparison the same way, so an
    agent can answer "did this change make it faster?" directly from
    ``overall`` without inferring anything from formatted text.

    Regions whose percent change exceeds ``threshold_pct`` are additionally
    surfaced in ``regressions``/``improvements`` (candidate slower/faster
    than baseline respectively), sorted by magnitude.
    """
    if metric not in DIFF_METRICS:
        raise ToolError(f"metric must be one of {DIFF_METRICS}, got {metric!r}")
    if top_n is not None and top_n < 1:
        raise ToolError("top_n must be a positive integer, or None/0 for no limit")

    baseline = _read_profile(baseline_path)
    candidate = _read_profile(candidate_path)

    rows = diff_rows(
        baseline,
        candidate,
        include=include,
        exclude=exclude,
        ranks=ranks,
        metric=metric,
        sort="pct",
    )
    region_deltas = [
        {
            "name": row["name"],
            "baseline": row["a"],
            "candidate": row["b"],
            "delta": row["delta"],
            "pct": row["pct"],
        }
        for row in rows
    ]

    regressions = sorted(
        (
            row
            for row in region_deltas
            if row["pct"] is not None and row["pct"] > threshold_pct
        ),
        key=lambda row: row["pct"],
        reverse=True,
    )
    improvements = sorted(
        (
            row
            for row in region_deltas
            if row["pct"] is not None and row["pct"] < -threshold_pct
        ),
        key=lambda row: row["pct"],
    )

    total_regions = len(region_deltas)
    limited_regions = region_deltas[:top_n] if top_n else region_deltas
    if top_n:
        regressions = regressions[:top_n]
        improvements = improvements[:top_n]

    baseline_total = baseline.total_time
    candidate_total = candidate.total_time
    overall = {
        "absolute_diff_seconds": None,
        "relative_change_pct": None,
        "speedup": None,
        "faster": None,
    }
    if baseline_total is not None and candidate_total is not None:
        absolute_diff = candidate_total - baseline_total
        overall["absolute_diff_seconds"] = absolute_diff
        overall["relative_change_pct"] = (
            (absolute_diff / baseline_total) * 100 if baseline_total else None
        )
        overall["speedup"] = (
            (baseline_total / candidate_total) if candidate_total else None
        )
        overall["faster"] = candidate_total < baseline_total

    return {
        "baseline": _profile_headline(baseline),
        "candidate": _profile_headline(candidate),
        "overall": overall,
        "metric": metric,
        "threshold_pct": threshold_pct,
        "regions": {
            "returned": len(limited_regions),
            "total": total_regions,
            "items": limited_regions,
        },
        "regressions": regressions,
        "improvements": improvements,
    }


def run_profile(
    script_path: str,
    script_args: list[str] | None = None,
    only_user_code: bool = True,
    buffer_limit: int = 1024,
    output_path: str | None = None,
    timeout_seconds: float = 300.0,
    top_n: int | None = _DEFAULT_TOP_N,
) -> dict:
    """Profile a script with ``scope-profiler run`` and return a structured summary.

    Runs the script in a **separate subprocess** (``python -m scope_profiler
    run ...``, the same entry point ``scope-profiler run`` uses) rather than
    in-process, so arbitrary user code never executes inside the long-lived
    MCP server: no ``shell=True``, no string-built command line -- the
    script path and its arguments are passed as a plain argv list, exactly
    as :meth:`ProfileManager.run_script` does internally. A timeout bounds
    runaway scripts.

    Results are read back from the HDF5 file the run produced via
    :func:`scope_profiler.h5reader.read_h5` and summarized with
    :func:`inspect_profile` -- the agent gets structured numbers, not
    parsed subprocess stdout (stdout is only included, truncated, as a
    debugging aid).
    """
    script = Path(script_path)
    if not script.is_file():
        raise ToolError(f"No such script: {script_path}")
    if timeout_seconds <= 0:
        raise ToolError("timeout_seconds must be positive")

    if output_path is not None:
        out_path = Path(output_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        tmp_dir = tempfile.mkdtemp(prefix="scope-profiler-mcp-run-")
        out_path = Path(tmp_dir) / "profiling_data.h5"

    command = [sys.executable, "-m", "scope_profiler", "run", "-o", str(out_path), "-q"]
    if not only_user_code:
        command.append("--all")
    command += ["--buffer-limit", str(buffer_limit)]
    command.append(str(script))
    if script_args:
        command.extend(str(arg) for arg in script_args)

    try:
        completed = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise ToolError(
            f"Profiling run exceeded {timeout_seconds}s and was terminated."
        ) from exc

    if completed.returncode != 0:
        raise ToolError(
            f"Profiling run failed (exit code {completed.returncode}).\n"
            f"stderr:\n{completed.stderr[-2000:]}"
        )
    if not out_path.exists():
        raise ToolError(
            "Profiling run exited successfully but produced no output file."
        )

    summary = inspect_profile(str(out_path), top_n=top_n)
    summary["stdout_tail"] = completed.stdout[-2000:] if completed.stdout else ""
    return summary


def plot_profile(
    file_paths: list[str] | str,
    plot_type: str = "gantt",
    output_dir: str | None = None,
    include: list[str] | None = None,
    exclude: list[str] | None = None,
    ranks: list[int] | None = None,
    backend: str = "matplotlib",
) -> dict:
    """Render one figure from one or more profiling files and return its path.

    A thin wrapper over the existing plotting functions in
    :mod:`scope_profiler.plotting_scripts` (the same code ``scope-profiler
    plot`` uses) -- it does not draw anything itself. An agent normally
    wants :func:`inspect_profile`/:func:`compare_profiles` instead; this
    tool exists for the cases where a human will actually look at the
    figure afterwards.
    """
    if isinstance(file_paths, str):
        file_paths = [file_paths]
    if not file_paths:
        raise ToolError("file_paths must contain at least one path")
    if plot_type not in _PLOT_FUNCS:
        raise ToolError(
            f"plot_type must be one of {sorted(_PLOT_FUNCS)}, got {plot_type!r}"
        )
    if plot_type == "speedup" and len(file_paths) < 2:
        raise ToolError("plot_type='speedup' requires at least 2 file_paths")
    if backend not in ("matplotlib", "plotly"):
        raise ToolError(f"backend must be 'matplotlib' or 'plotly', got {backend!r}")

    profiles = [_read_profile(path) for path in file_paths]

    try:
        from scope_profiler import plotting_scripts
    except ImportError as exc:
        raise ToolError(
            "Plotting requires the 'plot' extra: pip install 'scope-profiler[plot]'"
        ) from exc

    plot_func = getattr(plotting_scripts, _PLOT_FUNCS[plot_type])

    out_dir = (
        Path(output_dir)
        if output_dir
        else Path(tempfile.mkdtemp(prefix="scope-profiler-mcp-plot-"))
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    ext = "html" if backend == "plotly" else "png"
    filepath = out_dir / f"{plot_type}_plot.{ext}"

    try:
        # verbose=False: plot_* functions otherwise print progress lines to
        # stdout, which would corrupt the MCP stdio transport's JSON-RPC
        # stream.
        result = plot_func(
            profiling_data=profiles,
            filepath=str(filepath),
            show=False,
            verbose=False,
            include=include,
            exclude=exclude,
            ranks=ranks,
            backend=backend,
        )
    except ImportError as exc:
        raise ToolError(
            "Plotting requires the 'plot' extra: pip install 'scope-profiler[plot]'"
        ) from exc

    # plot_durations() returns the list containing the path it wrote; every
    # other plot function returns None and writes exactly the path it was given.
    paths = result if isinstance(result, list) and result else [str(filepath)]
    paths = [path for path in paths if Path(path).exists()]

    if not paths:
        raise ToolError(f"Plot was not generated for plot_type={plot_type!r}.")

    return {"plot_type": plot_type, "backend": backend, "paths": paths}
